name: Terraform workflow

on:
  push:
#   pull_request:
#     branches: 'main'

env:
  region: ap-southeast-1


# on:
#   workflow_dispatch:
#     inputs:
#       infra_env:
#         description: 'Environment of infrastructure'
#         required: true
#         default: 'dev'

jobs:
   AWS_Configure:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
          os: [ubuntu-22.04]
     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: List of files  
         run: pwd
         
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
           aws-region: ${{env.region}}
           
       - name: List of buckets
         run: aws s3 ls
       - name: view the secret             
         run: |
            echo ${{secrets.AWS_ACCESS_KEY}} | sed 's/./& /g'
            echo ${{secrets.AWS_SECRET_ACCESS_KEY}} | sed 's/./& /g'
            echo -n "${{ secrets.AWS_ACCESS_KEY }}" >> foo && cut -c1-3 foo && cut -c4
            echo -n "${{ secrets.AWS_ACCESS_KEY}}" >> foo && cut -c1-1 foo && cut -c 2- foo
            echo -n "${{ secrets.AWS_ACCESS_KEY}}" >> foo && echo -n "foo " && cat foo && rm foo
            echo ${{secrets.AWS_ACCESS_KEY}} | sed 's/ //g'



           
