name: Terraform workflow

on:
  push:
#   pull_request:
#     branches: 'main'

env:
  region: ap-southeast-1


# on:
#   workflow_dispatch:
#     inputs:
#       infra_env:
#         description: 'Environment of infrastructure'
#         required: true
#         default: 'dev'

jobs:
   AWS_Configure:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: List of files  
         run: pwd
         
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
           aws-region: ${{env.region}}
           
       - name: List of buckets
         run: aws s3 ls
