name: Python scripts
on:
  push

jobs:
  python-version:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: check python version
        run: python --version
